### ISSUE TITLE
[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called

### ISSUE THREAD

**Issue by coatezy** [klaviyo/klaviyo-api-ruby#13]
After adding the [klaviyo-api-ruby](https://github.com/klaviyo/klaviyo-api-ruby) gem to a Ruby on Rails project and making an API request the following error is thrown which is caused by one of the gem's dependencies (Typhoeus).

```
[a149eed0-66c7-4910-bf27-747435503690] ETHON: Libcurl initialized
objc[56523]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.
objc[56523]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
```

More information can be found in this issue https://github.com/typhoeus/typhoeus/issues/687.

**System configuration**
Rails version: Rails 6.1.6.1
Ruby version: ruby 3.0.4p208 (2022-04-12 revision 3fa771dded) [arm64-darwin21]

**Comment by dano-klaviyo** [comment]
Thanks for flagging this. We will take a look. Did the workaround described in the issue work for you?

**Comment by captainbooker** [comment]
currently experiencing the same error. The workaround did not work for me

**Comment by coatezy** [comment]
The work around did work for me locally but as the underlying issue and impact is not fully understood I did not want to risk using it in production so have implemented a solution using another HTTP client in the meantime.

**Comment by llfcampbell** [comment]
I would recommend only running these requests inside a background job(activejob) so errors will be properly thrown into stdout.
