### ISSUE TITLE
Is the gem working ?

### ISSUE THREAD

**Issue by subintp** [klaviyo/klaviyo-api-ruby#19]
Getting this error for all the requests with valid credentials 

` {"errors":[{"id":"f2b6a3ee-9d8b-45f1-87a8-e035418cd5c1","status":401,"code":"not_authenticated","title":"Authentication credentials were not provided.","detail":"Missing or invalid authorization scheme. Please use Klaviyo-API-Key.","source":{"pointer":"/data/"}}]}`

**Comment by Ian-Montgomery-Klaviyo** [comment]
You might be missing the key prefix `Klaviyo-API-Key`, which makes your api key look something like this:

```
# Setup authorization
KlaviyoAPI.configure do |config|
config.api_key['Klaviyo-API-Key'] = 'Klaviyo-API-Key PKHERE'
```

If this isn't the issue, can you post a small snippet of some of your code (With api key removed).

**Comment by theHeadMike** [comment]
Yes, the gem works. 
The redundant Klaviyo prefix also through me for a bit.
This does work though:
```
KlaviyoAPI.configure do |config|
  config.api_key['Klaviyo-API-Key'] = "Klaviyo-API-Key #{Rails.application.secrets.klaviyo_api_key}"
end
```
