### ISSUE TITLE
Is it possible to use OAuth access tokens to make API calls with this gem? 

### ISSUE THREAD

**Issue by alfredoshopcreatify** [klaviyo/klaviyo-api-ruby#20]
As the title says, is this possible?   

Is there an equivalent to the code below using an OAuth access token?  
`# Setup authorization`
`KlaviyoAPI.configure do |config|`
    `config.api_key['Klaviyo-API-Key'] = 'Klaviyo-API-Key your-api-key'`
     `#config.max_retries = 5 # optional`
     `#config.max_delay = 60 # optional`
`end`

**Comment by Ian-Montgomery-Klaviyo** [comment]
There is no official OAuth support for Ruby at the moment. However, you can still override your request header and pass in your access token for authentication. Doing this would look something like this:

```ruby
require 'klaviyo-api-sdk'
begin
# Setup authorization
KlaviyoAPI.configure

result = KlaviyoAPI::Profiles.get_profiles({
    header_params: {
        'Authorization': 'Bearer YOUR_ACCESS_TOKEN',
      }
})
puts result
end
```

**Comment by alfredoshopcreatify** [comment]
Awesome!  That should work for me.  Thanks so much.

**Comment by alexdunae** [comment]
Hi @Ian-Montgomery-Klaviyo  I don't think this should be closed.  I've been struggling trying to get this library working with oauth2 + pkce and it's not been easy.  Given that oauth2 is recommended for building Klaviyo apps it seems this issue should remain open until it's actually resolved.
