### ISSUE TITLE
How do I use the SDK with Bearer access tokens?

### ISSUE THREAD

**Issue by esb** [klaviyo/klaviyo-api-ruby#24]
I'm not finding anything that allows me to use the SDK using a bearer access token from an OAuth2 authintication.

Surely the package isn't missing this kind of support?

**Comment by Ian-Montgomery-Klaviyo** [comment]
OAuth isn't currently support but will be coming shortly.

**Comment by Ian-Montgomery-Klaviyo** [comment]
It is however possible to bypass the api key and just pass your header in as a query paramerter 

```
KlaviyoAPI.configure do |config|
# don't put api-key here like normal
end

key = "Bearer #{$YOUR_KEY_KEY}"
response = KlaviyoAPI::Accounts.get_accounts({
  header_params: {
    'Authorization': key,
  },
})
```
