### ISSUE TITLE
Working with multiple API keys

### ISSUE THREAD

**Issue by hadaromash** [klaviyo/klaviyo-api-ruby#27]
Our app is a b2b service that serves multiple accounts, each has its own API key. Any ability to provide the API key as a parameter for revery single API request?

**Comment by dano-klaviyo** [comment]
Hi, @hadaromash , yes it is possible: https://github.com/klaviyo/klaviyo-api-ruby?tab=readme-ov-file#per-request-api-key

**Comment by hadaromash** [comment]
Thanks @dano-klaviyo ! Totally missed it.
For future versions might be nice to support providing the api key in the `opts` object.

**Comment by hadaromash** [comment]
Thanks @dano-klaviyo ! Totally missed it.
For future versions might be nice to support providing the api key in the opts object.
