### ISSUE TITLE
Gem does not work with Ruby 3.2.4

### ISSUE THREAD

**Issue by noctivityinc** [klaviyo/klaviyo-api-ruby#29]
When running any method with Ruby 3.2.4 on Rails 6.1.7.8 you get this error:

```
3.2.4 :018 > body
 => {:data=>{:type=>"profile", :attributes=>{:email=>"kt1@test.com", :first_name=>"K", :last_name=>"Test 1", :properties=>{:role=>"guest", :channel=>"Natural"}}}}
3.2.4 :019 > profile = KlaviyoAPI::Profiles.create_profile(body)
objc[39475]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.
objc[39475]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
```

Making the gem unusable.  Please advise

**Comment by ben-horgan-1** [comment]
Thanks for bringing this up- we'll look into it. It most likely has to do with either the MacOS version or the `typhoeus` library. In the meantime, there may be some helpful workarounds in these threads:

- https://github.com/klaviyo/klaviyo-api-ruby/issues/13
- https://github.com/typhoeus/typhoeus/issues/687
- https://github.com/rails/rails/issues/38560

**Comment by ben-horgan-1** [comment]
You should be able to do either of the following to resolve this:

- Add `export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES` to your `.zshrc` or `.bashrc`, then restart your terminal (see [this](https://github.com/rails/rails/issues/38560#issuecomment-590236052))
- Add a file `config/initializers/ethon.rb` with the following contents (see [this](https://github.com/typhoeus/typhoeus/issues/687#issuecomment-2087890569)):
  ```
  require 'ethon'
  Ethon::Curl.init
  ```

Let us know if either of these resolves your issue.

**Comment by noctivityinc** [comment]
Yes adding ethon did fix the problem, but this seems like a band-aid and I
dont know what else it might impact.  Are you planning on fixing this gem?

**Comment by ben-horgan-1** [comment]
We're looking into potential fixes. The issue appears to be that a request library we use, Typhoeus, is not compatible with Spring (or `Process.fork` in general). This does not have to do with our code, and only occurs on macOS. We will investigate potential solutions.
