### ISSUE TITLE
README outdated

### ISSUE THREAD

**Issue by Alagaesia93** [klaviyo/klaviyo-api-ruby#4]
Hey there!
I'm trying to use this gem and I have some issues

`KlaviyoAPI::Events.get_events(opts)` => uninitialized constant KlaviyoAPI::Events (NameError) Did you mean? 
 KlaviyoAPI::EventsApi

probably an outdated README?

Another thing I need to do is to do dynamic api_key and api_secret. This is what I came up, but it still gives me 401
```ruby
config = KlaviyoAPI::Configuration.new
config.api_key = <API_KEY>
config.access_token = <SECRET_KEY>
api_client = KlaviyoAPI::ApiClient.new(config)

KlaviyoAPI::EventsApi.new(api_client).get_events
```

Can you help me please?

**Comment by dano-klaviyo** [comment]
Hi @Alagaesia93 , you need to configure your client as described in the documentation otherwise you might get unexpected results:

```ruby
# Setup authorization
KlaviyoAPI.configure do |config|
  config.api_key['Klaviyo-API-Key'] = 'Klaviyo-API-Key your-api-key'
  #config.max_retries = 5 # optional
  #config.max_delay = 60 # optional
end
```

to use a different private key per call you can do this:
```ruby
response = KlaviyoAPI::Events.get_events({
  header_params: {
    'Authorization': 'Klaviyo-API-Key your-api-key',
  },
  debug_auth_names: []
})
```

The client doesn't require an access token.

**Comment by Alagaesia93** [comment]
Ok thanks a lot for the custom key.

The problem is that `KlaviyoAPI::Events` is not defined, should it be `KlaviyoAPI::EventsApi`

**Comment by dano-klaviyo** [comment]
So we use some wrapper logic to strip out the `Api` suffix. If you configure the client as noted above, you should be able to use `KlaviyoAPI::Events`
